//
//  CountriesData.swift
//  CDXplore
//
//  Created by Cristi Sandu on 16.12.2025.
//


import Foundation

enum CountriesData {
    static let all: [Country] = [
        // Europe (44)
        .init(code: "AL", name: "Albania", continent: "Europe"),
        .init(code: "AD", name: "Andorra", continent: "Europe"),
        .init(code: "AT", name: "Austria", continent: "Europe"),
        .init(code: "BY", name: "Belarus", continent: "Europe"),
        .init(code: "BE", name: "Belgium", continent: "Europe"),
        .init(code: "BA", name: "Bosnia and Herzegovina", continent: "Europe"),
        .init(code: "BG", name: "Bulgaria", continent: "Europe"),
        .init(code: "HR", name: "Croatia", continent: "Europe"),
        .init(code: "CZ", name: "Czech Republic", continent: "Europe"),
        .init(code: "CY", name: "Cyprus", continent: "Europe"),
        .init(code: "DK", name: "Denmark", continent: "Europe"),
        .init(code: "EE", name: "Estonia", continent: "Europe"),
        .init(code: "FI", name: "Finland", continent: "Europe"),
        .init(code: "FR", name: "France", continent: "Europe"),
        .init(code: "DE", name: "Germany", continent: "Europe"),
        .init(code: "GR", name: "Greece", continent: "Europe"),
        .init(code: "HU", name: "Hungary", continent: "Europe"),
        .init(code: "IS", name: "Iceland", continent: "Europe"),
        .init(code: "IE", name: "Ireland", continent: "Europe"),
        .init(code: "IT", name: "Italy", continent: "Europe"),
        .init(code: "LV", name: "Latvia", continent: "Europe"),
        .init(code: "LI", name: "Liechtenstein", continent: "Europe"),
        .init(code: "LT", name: "Lithuania", continent: "Europe"),
        .init(code: "LU", name: "Luxembourg", continent: "Europe"),
        .init(code: "MT", name: "Malta", continent: "Europe"),
        .init(code: "MD", name: "Moldova", continent: "Europe"),
        .init(code: "MC", name: "Monaco", continent: "Europe"),
        .init(code: "ME", name: "Montenegro", continent: "Europe"),
        .init(code: "NL", name: "Netherlands", continent: "Europe"),
        .init(code: "MK", name: "North Macedonia", continent: "Europe"),
        .init(code: "NO", name: "Norway", continent: "Europe"),
        .init(code: "PL", name: "Poland", continent: "Europe"),
        .init(code: "PT", name: "Portugal", continent: "Europe"),
        .init(code: "RO", name: "Romania", continent: "Europe"),
        .init(code: "RU", name: "Russia", continent: "Europe"),
        .init(code: "SM", name: "San Marino", continent: "Europe"),
        .init(code: "RS", name: "Serbia", continent: "Europe"),
        .init(code: "SK", name: "Slovakia", continent: "Europe"),
        .init(code: "SI", name: "Slovenia", continent: "Europe"),
        .init(code: "ES", name: "Spain", continent: "Europe"),
        .init(code: "SE", name: "Sweden", continent: "Europe"),
        .init(code: "CH", name: "Switzerland", continent: "Europe"),
        .init(code: "UA", name: "Ukraine", continent: "Europe"),
        .init(code: "GB", name: "United Kingdom", continent: "Europe"),
        .init(code: "VA", name: "Vatican City", continent: "Europe"),

        // Asia (48)
        .init(code: "AF", name: "Afghanistan", continent: "Asia"),
        .init(code: "AM", name: "Armenia", continent: "Asia"),
        .init(code: "AZ", name: "Azerbaijan", continent: "Asia"),
        .init(code: "BH", name: "Bahrain", continent: "Asia"),
        .init(code: "BD", name: "Bangladesh", continent: "Asia"),
        .init(code: "BT", name: "Bhutan", continent: "Asia"),
        .init(code: "BN", name: "Brunei", continent: "Asia"),
        .init(code: "KH", name: "Cambodia", continent: "Asia"),
        .init(code: "CN", name: "China", continent: "Asia"),
        .init(code: "GE", name: "Georgia", continent: "Asia"),
        .init(code: "IN", name: "India", continent: "Asia"),
        .init(code: "ID", name: "Indonesia", continent: "Asia"),
        .init(code: "IR", name: "Iran", continent: "Asia"),
        .init(code: "IQ", name: "Iraq", continent: "Asia"),
        .init(code: "IL", name: "Israel", continent: "Asia"),
        .init(code: "JP", name: "Japan", continent: "Asia"),
        .init(code: "JO", name: "Jordan", continent: "Asia"),
        .init(code: "KZ", name: "Kazakhstan", continent: "Asia"),
        .init(code: "KW", name: "Kuwait", continent: "Asia"),
        .init(code: "KG", name: "Kyrgyzstan", continent: "Asia"),
        .init(code: "LA", name: "Laos", continent: "Asia"),
        .init(code: "LB", name: "Lebanon", continent: "Asia"),
        .init(code: "MY", name: "Malaysia", continent: "Asia"),
        .init(code: "MV", name: "Maldives", continent: "Asia"),
        .init(code: "MN", name: "Mongolia", continent: "Asia"),
        .init(code: "MM", name: "Myanmar", continent: "Asia"),
        .init(code: "NP", name: "Nepal", continent: "Asia"),
        .init(code: "KP", name: "North Korea", continent: "Asia"),
        .init(code: "OM", name: "Oman", continent: "Asia"),
        .init(code: "PK", name: "Pakistan", continent: "Asia"),
        .init(code: "PS", name: "Palestine", continent: "Asia"),
        .init(code: "PH", name: "Philippines", continent: "Asia"),
        .init(code: "QA", name: "Qatar", continent: "Asia"),
        .init(code: "SA", name: "Saudi Arabia", continent: "Asia"),
        .init(code: "SG", name: "Singapore", continent: "Asia"),
        .init(code: "KR", name: "South Korea", continent: "Asia"),
        .init(code: "LK", name: "Sri Lanka", continent: "Asia"),
        .init(code: "SY", name: "Syria", continent: "Asia"),
        .init(code: "TJ", name: "Tajikistan", continent: "Asia"),
        .init(code: "TH", name: "Thailand", continent: "Asia"),
        .init(code: "TL", name: "Timor-Leste", continent: "Asia"),
        .init(code: "TR", name: "Turkey", continent: "Asia"),
        .init(code: "TM", name: "Turkmenistan", continent: "Asia"),
        .init(code: "AE", name: "United Arab Emirates", continent: "Asia"),
        .init(code: "UZ", name: "Uzbekistan", continent: "Asia"),
        .init(code: "VN", name: "Vietnam", continent: "Asia"),
        .init(code: "YE", name: "Yemen", continent: "Asia"),

        // Africa (54)
        .init(code: "DZ", name: "Algeria", continent: "Africa"),
        .init(code: "AO", name: "Angola", continent: "Africa"),
        .init(code: "BJ", name: "Benin", continent: "Africa"),
        .init(code: "BW", name: "Botswana", continent: "Africa"),
        .init(code: "BF", name: "Burkina Faso", continent: "Africa"),
        .init(code: "BI", name: "Burundi", continent: "Africa"),
        .init(code: "CV", name: "Cape Verde", continent: "Africa"),
        .init(code: "CM", name: "Cameroon", continent: "Africa"),
        .init(code: "CF", name: "Central African Republic", continent: "Africa"),
        .init(code: "TD", name: "Chad", continent: "Africa"),
        .init(code: "KM", name: "Comoros", continent: "Africa"),
        .init(code: "CG", name: "Congo", continent: "Africa"),
        .init(code: "CD", name: "Democratic Republic of the Congo", continent: "Africa"),
        .init(code: "CI", name: "Côte d’Ivoire", continent: "Africa"),
        .init(code: "DJ", name: "Djibouti", continent: "Africa"),
        .init(code: "EG", name: "Egypt", continent: "Africa"),
        .init(code: "GQ", name: "Equatorial Guinea", continent: "Africa"),
        .init(code: "ER", name: "Eritrea", continent: "Africa"),
        .init(code: "SZ", name: "Eswatini", continent: "Africa"),
        .init(code: "ET", name: "Ethiopia", continent: "Africa"),
        .init(code: "GA", name: "Gabon", continent: "Africa"),
        .init(code: "GM", name: "Gambia", continent: "Africa"),
        .init(code: "GH", name: "Ghana", continent: "Africa"),
        .init(code: "GN", name: "Guinea", continent: "Africa"),
        .init(code: "GW", name: "Guinea-Bissau", continent: "Africa"),
        .init(code: "KE", name: "Kenya", continent: "Africa"),
        .init(code: "LS", name: "Lesotho", continent: "Africa"),
        .init(code: "LR", name: "Liberia", continent: "Africa"),
        .init(code: "LY", name: "Libya", continent: "Africa"),
        .init(code: "MG", name: "Madagascar", continent: "Africa"),
        .init(code: "MW", name: "Malawi", continent: "Africa"),
        .init(code: "ML", name: "Mali", continent: "Africa"),
        .init(code: "MR", name: "Mauritania", continent: "Africa"),
        .init(code: "MU", name: "Mauritius", continent: "Africa"),
        .init(code: "MA", name: "Morocco", continent: "Africa"),
        .init(code: "MZ", name: "Mozambique", continent: "Africa"),
        .init(code: "NA", name: "Namibia", continent: "Africa"),
        .init(code: "NE", name: "Niger", continent: "Africa"),
        .init(code: "NG", name: "Nigeria", continent: "Africa"),
        .init(code: "RW", name: "Rwanda", continent: "Africa"),
        .init(code: "ST", name: "São Tomé and Príncipe", continent: "Africa"),
        .init(code: "SN", name: "Senegal", continent: "Africa"),
        .init(code: "SC", name: "Seychelles", continent: "Africa"),
        .init(code: "SL", name: "Sierra Leone", continent: "Africa"),
        .init(code: "SO", name: "Somalia", continent: "Africa"),
        .init(code: "ZA", name: "South Africa", continent: "Africa"),
        .init(code: "SS", name: "South Sudan", continent: "Africa"),
        .init(code: "SD", name: "Sudan", continent: "Africa"),
        .init(code: "TZ", name: "Tanzania", continent: "Africa"),
        .init(code: "TG", name: "Togo", continent: "Africa"),
        .init(code: "TN", name: "Tunisia", continent: "Africa"),
        .init(code: "UG", name: "Uganda", continent: "Africa"),
        .init(code: "ZM", name: "Zambia", continent: "Africa"),
        .init(code: "ZW", name: "Zimbabwe", continent: "Africa"),

        // North America (23)
        .init(code: "AG", name: "Antigua and Barbuda", continent: "North America"),
        .init(code: "BS", name: "Bahamas", continent: "North America"),
        .init(code: "BB", name: "Barbados", continent: "North America"),
        .init(code: "BZ", name: "Belize", continent: "North America"),
        .init(code: "CA", name: "Canada", continent: "North America"),
        .init(code: "CR", name: "Costa Rica", continent: "North America"),
        .init(code: "CU", name: "Cuba", continent: "North America"),
        .init(code: "DM", name: "Dominica", continent: "North America"),
        .init(code: "DO", name: "Dominican Republic", continent: "North America"),
        .init(code: "SV", name: "El Salvador", continent: "North America"),
        .init(code: "GD", name: "Grenada", continent: "North America"),
        .init(code: "GT", name: "Guatemala", continent: "North America"),
        .init(code: "HT", name: "Haiti", continent: "North America"),
        .init(code: "HN", name: "Honduras", continent: "North America"),
        .init(code: "JM", name: "Jamaica", continent: "North America"),
        .init(code: "MX", name: "Mexico", continent: "North America"),
        .init(code: "NI", name: "Nicaragua", continent: "North America"),
        .init(code: "PA", name: "Panama", continent: "North America"),
        .init(code: "KN", name: "Saint Kitts and Nevis", continent: "North America"),
        .init(code: "LC", name: "Saint Lucia", continent: "North America"),
        .init(code: "VC", name: "Saint Vincent and the Grenadines", continent: "North America"),
        .init(code: "TT", name: "Trinidad and Tobago", continent: "North America"),
        .init(code: "US", name: "United States", continent: "North America"),

        // South America (12)
        .init(code: "AR", name: "Argentina", continent: "South America"),
        .init(code: "BO", name: "Bolivia", continent: "South America"),
        .init(code: "BR", name: "Brazil", continent: "South America"),
        .init(code: "CL", name: "Chile", continent: "South America"),
        .init(code: "CO", name: "Colombia", continent: "South America"),
        .init(code: "EC", name: "Ecuador", continent: "South America"),
        .init(code: "GY", name: "Guyana", continent: "South America"),
        .init(code: "PY", name: "Paraguay", continent: "South America"),
        .init(code: "PE", name: "Peru", continent: "South America"),
        .init(code: "SR", name: "Suriname", continent: "South America"),
        .init(code: "UY", name: "Uruguay", continent: "South America"),
        .init(code: "VE", name: "Venezuela", continent: "South America"),

        // Oceania (14)
        .init(code: "AU", name: "Australia", continent: "Oceania"),
        .init(code: "FJ", name: "Fiji", continent: "Oceania"),
        .init(code: "KI", name: "Kiribati", continent: "Oceania"),
        .init(code: "MH", name: "Marshall Islands", continent: "Oceania"),
        .init(code: "FM", name: "Micronesia", continent: "Oceania"),
        .init(code: "NR", name: "Nauru", continent: "Oceania"),
        .init(code: "NZ", name: "New Zealand", continent: "Oceania"),
        .init(code: "PW", name: "Palau", continent: "Oceania"),
        .init(code: "PG", name: "Papua New Guinea", continent: "Oceania"),
        .init(code: "WS", name: "Samoa", continent: "Oceania"),
        .init(code: "SB", name: "Solomon Islands", continent: "Oceania"),
        .init(code: "TO", name: "Tonga", continent: "Oceania"),
        .init(code: "TV", name: "Tuvalu", continent: "Oceania"),
        .init(code: "VU", name: "Vanuatu", continent: "Oceania"),
    ]
}
